### ISSUE TITLE
pkg_gpgcheck is always enabled

### ISSUE THREAD

**Issue by mattiasgiese** [openSUSE/zypp-plugin-spacewalk#34]
Observed on a SLES 12 SP2 Host with zypp-plugin-spacewalk-1.0.0-1.1.noarch installed (coming from the public build service). The server is running Spacewalk 2.7 with latest patches applied.
`utf8_encode(channel.dict.get('gpgcheck', "1"))` will always return 1 and does not regard the configuration of the software channel in Spacewalk.

**Comment by mcalmer** [comment]
Original spacewalk server do not send info about gpg-check enabled or disabled. So we have to choose the save option and set it to enabled.

**Comment by mattiasgiese** [comment]
Okay, so yeah, the safe option is to set it to enabled. But what if the user wants to disable it globally?
zypp-plugin-spacewalk should have an configuration option to tweak the repository generation.
